# 1) Importar las Librerías



In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import cv2

# 2) Definicion de Matrices




In [ ]:
# RECTA

A = np.array([[4,0,-3],[-7,2,6]])
B = np.array([[-1,-4,3],[8,2,-9]])

C = np.array([[4,0,-3],[-7,2,6]])
D = np.array([[5,1],[-10,3],[2,6]])

E = np.array([[1,1,1],[2,2,2],[3,3,3]])

suma = np.add(A,B)
mult = np.dot(C,D)
print('Resultado de la suma: ')
print(suma)
print('Resultado de la multiplicacion: ')
print(mult)

print(E)
print('Resultado de la transposicion: ')
print(E.transpose())





Resultado de la suma: 
[[ 3 -4  0]
 [ 1  4 -3]]
Resultado de la multiplicacion: 
[[ 14 -14]
 [-43  35]]
[[1 1 1]
 [2 2 2]
 [3 3 3]]
Resultado de la transposicion: 
[[1 2 3]
 [1 2 3]
 [1 2 3]]
